In [1]:
import numpy as np

In [21]:
y = np.array([1,2,3,4,5,6,7,8]).reshape(-1, 1)
y

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [24]:
y[5:, :]

array([[6],
       [7],
       [8]])

In [11]:
X.reshape((2,-1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
X.reshape((-1, 2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])