In [24]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Input, Dense

In [51]:
model = Sequential([Input(3), Dense(5, activation="relu"), Dense(3)])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 5)                 20        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 18        
Total params: 38
Trainable params: 38
Non-trainable params: 0
_________________________________________________________________


In [9]:
20 == (3 + 1)*5
18 == (5 + 1)*3

True

In [52]:
[L0, L1] = model.layers

In [23]:
w, b = L0.get_weights();
w, b = L1.get_weights();
print(w, b)

[[ 0.4114409   0.6716798  -0.81279117]
 [-0.3838969   0.78592175 -0.52853346]
 [-0.7973067   0.26151747  0.20389539]
 [-0.4304435   0.05076534 -0.7916771 ]
 [ 0.10459918  0.6192481  -0.26238936]] [0. 0. 0.]


In [27]:
X = np.random.uniform(size=(10, 3)).astype(np.float32)

In [28]:
model(X)

<tf.Tensor: id=157, shape=(10, 3), dtype=float32, numpy=
array([[-0.0381803 , -0.04984014, -0.03025628],
       [-0.19904512, -0.10622066, -0.28970954],
       [-0.22452259, -0.5222389 ,  0.6836453 ],
       [ 0.2467139 , -0.5073025 ,  0.10420934],
       [ 0.34927934, -0.8107095 ,  0.6382964 ],
       [-0.2120727 , -0.46634492,  0.27665117],
       [ 0.2124318 , -0.77573234,  0.8613352 ],
       [-0.38946185,  0.01207036, -0.32225734],
       [ 0.10143188, -0.28381658, -0.20980367],
       [-0.43004823, -0.21648732, -0.07274511]], dtype=float32)>

In [31]:
L1(L0(X)) == model(X)

<tf.Tensor: id=190, shape=(10, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

In [32]:
model(X).__class__

tensorflow.python.framework.ops.EagerTensor

In [33]:
X[1, 2] = 100

In [35]:
Y = model(X)
Y[1, 2] = 333.01

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [36]:
np.array(Y)

array([[-3.8180295e-02, -4.9840141e-02, -3.0256284e-02],
       [ 3.1463261e+01, -8.8077078e+00, -5.1045147e+01],
       [-2.2452259e-01, -5.2223891e-01,  6.8364531e-01],
       [ 2.4671391e-01, -5.0730252e-01,  1.0420934e-01],
       [ 3.4927934e-01, -8.1070948e-01,  6.3829643e-01],
       [-2.1207270e-01, -4.6634492e-01,  2.7665117e-01],
       [ 2.1243180e-01, -7.7573234e-01,  8.6133522e-01],
       [-3.8946185e-01,  1.2070362e-02, -3.2225734e-01],
       [ 1.0143188e-01, -2.8381658e-01, -2.0980367e-01],
       [-4.3004823e-01, -2.1648732e-01, -7.2745107e-02]], dtype=float32)

In [41]:
tf.constant(X)

<tf.Tensor: id=222, shape=(10, 3), dtype=float32, numpy=
array([[1.20044261e-01, 6.02847934e-02, 1.47270754e-01],
       [5.40726423e-01, 1.24903575e-01, 1.00000000e+02],
       [4.31078643e-01, 7.02405989e-01, 3.12936269e-02],
       [1.69672877e-01, 5.53849161e-01, 9.36358690e-01],
       [4.28421125e-02, 9.38607156e-01, 7.69995630e-01],
       [6.01371527e-01, 5.96217692e-01, 5.37308335e-01],
       [4.34487686e-02, 9.41989839e-01, 3.40512693e-01],
       [6.74118340e-01, 1.59293413e-02, 4.25905824e-01],
       [3.03247154e-01, 2.89260983e-01, 9.30030167e-01],
       [8.19912195e-01, 3.09342921e-01, 5.21750450e-01]], dtype=float32)>

In [42]:
w, b = L0.get_weights()

In [43]:
w

array([[-0.7079137 ,  0.5788818 ,  0.05704391,  0.5468034 ,  0.1128931 ],
       [-0.6462908 , -0.47961363, -0.03402877, -0.44881743,  0.07530403],
       [ 0.4602515 ,  0.27622634, -0.47217923,  0.13277578, -0.80270195]],
      dtype=float32)

In [44]:
b

array([0., 0., 0., 0., 0.], dtype=float32)

In [55]:
keras.activations.relu(X.dot(w) + b.reshape(1, -1)) - L0(X)

<tf.Tensor: id=322, shape=(10, 5), dtype=float32, numpy=
array([[-5.22373170e-02,  8.12580884e-02,  0.00000000e+00,
        -6.01093099e-02, -6.07234314e-02],
       [ 5.91940689e+00,  2.78757458e+01, -2.91932068e+01,
        -1.56777706e+01,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -3.12938869e-01, -6.18435919e-01],
       [-2.23543629e-01,  9.12338644e-02,  0.00000000e+00,
        -4.08107311e-01, -1.47487002e-03],
       [-3.12187783e-02,  0.00000000e+00,  0.00000000e+00,
        -3.09531331e-01, -1.75360948e-01],
       [-9.50825363e-02,  2.10587621e-01,  0.00000000e+00,
        -4.21259165e-01, -5.47492385e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.86152786e-01, -3.71078879e-01],
       [-2.29981601e-01,  5.00241339e-01,  0.00000000e+00,
        -1.09046966e-01, -3.53935987e-01],
       [-2.86064178e-01,  2.93709576e-01,  0.00000000e+00,
        -3.09289277e-01,  0.00000000e+00],
       [-1.95287108e-01, 

<tf.Tensor: id=229, shape=(10, 5), dtype=float32, numpy=
array([[-5.6160901e-02,  8.1258088e-02, -6.4741813e-02,  5.8137737e-02,
        -1.0012266e-01],
       [ 4.5561638e+01,  2.7875746e+01, -4.7191330e+01,  1.3517191e+01,
        -8.0199745e+01],
       [-7.4472207e-01, -7.8695782e-02, -1.4087799e-02, -7.5381748e-02,
         7.6440357e-02],
       [-4.7100846e-02,  9.1233864e-02, -4.5129713e-01, -3.1473689e-02,
        -6.9075495e-01],
       [-2.8255001e-01, -2.1267520e-01, -3.9307171e-01, -2.9560027e-01,
        -5.4255950e-01],
       [-5.6375217e-01,  2.1058762e-01, -2.3968981e-01,  1.3258064e-01,
        -3.1851014e-01],
       [-4.8283583e-01, -3.3258089e-01, -1.9035929e-01, -3.5381168e-01,
        -1.9748950e-01],
       [-2.9148880e-01,  5.0024134e-01, -1.6319160e-01,  4.1801080e-01,
        -2.6457259e-01],
       [ 2.6428265e-02,  2.9370958e-01, -4.3168572e-01,  1.5947668e-01,
        -6.9051999e-01],
       [-5.4021609e-01,  4.7038838e-01, -2.1011528e-01,  3.7876812e-01

In [56]:
model.compile(loss="mse", optimizer="sgd")

In [60]:
y = np.random.normal(size=(10,3))

In [62]:
model.fit(X, y, epochs=3)

Train on 10 samples
Epoch 1/3
10/10 [==============================] - 0s 838us/sample - loss: 1.1247
Epoch 2/3
10/10 [==============================] - 0s 189us/sample - loss: 1.1237
Epoch 3/3
10/10 [==============================] - 0s 142us/sample - loss: 1.1226


In [65]:
model = Sequential([Input(2),
                    Dense(10, "relu"),
                    Dense(20, "relu"),
                    Dense(1, activation="sigmoid")])
# sigmoid activation in output layer for binary classification problem

In [66]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 10)                30        
_________________________________________________________________
dense_13 (Dense)             (None, 20)                220       
_________________________________________________________________
dense_14 (Dense)             (None, 1)                 21        
Total params: 271
Trainable params: 271
Non-trainable params: 0
_________________________________________________________________


In [67]:
model.compile(loss="binary_crossentropy", optimizer="sgd")

In [69]:
X = np.random.uniform(size=(20, 2))
y = np.random.uniform(size=20)

In [70]:
model.fit(X, y, epochs=5)

Train on 20 samples
Epoch 1/5
20/20 [==============================] - 0s 14ms/sample - loss: 0.6982
Epoch 2/5
20/20 [==============================] - 0s 97us/sample - loss: 0.6981
Epoch 3/5
20/20 [==============================] - 0s 83us/sample - loss: 0.6980
Epoch 4/5
20/20 [==============================] - 0s 65us/sample - loss: 0.6980
Epoch 5/5
20/20 [==============================] - 0s 68us/sample - loss: 0.6979
